### ISSUE TITLE
UpdateUser and DeleteUser in User-Service reference userid instead of id

### ISSUE THREAD

**Issue by bateman001** [jcochran206/artsy-capstone-server#6]
`updateUser(db, userid, newUser) {

        return db('users')

            .where({

                userid: userid // needs to be id: userid

            })
            .update(newUser, returning = true)

            .returning('*')

    },

    deleteUser(db, userid) {

        return db('users')

            .where({

                userid: userid //needs to be id: userid

            })

            .delete()

    }`

**Comment by artificialarea** [comment]
Heya. In these kinds of instances — where you already know how to solve the bug — no need to make an issue ticket, per se. Just make the changes to the code and push to main...

**Comment by jcochran206** [comment]
fixed update and delete reviewed on post man
